# Generated by Django 5.1 on 2024-12-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_name',
            field=models.TextField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
