# Generated by Django 5.1 on 2024-12-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance_tracker', '0002_table_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='date',
        ),
    ]
