# Generated by Django 5.1 on 2024-12-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance_tracker', '0003_remove_table_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='user',
        ),
        migrations.AddField(
            model_name='tracker',
            name='type',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
